baseURL: "http://january3.github.io/statystycznakuchnia/"
languageCode: "pl"
DefaultContentLanguage: "pl"
title: "Kuchnia statystycznie istotna"
theme: "github.com/theNewDynamic/gohugo-theme-ananke"
#[params]
#  commentoEnable = true
#disqusShortname: "biokompost"
params:
  recent_posts_number: 6
  favicon: "images/favicon.png"
  cover_dimming_class: "bg-black-10"
  background_color_class: "bg-black-10"
  date_format: "2.1.2006"
  read_more_copy: "Więcej..."
  recent_copy: "Najnowsze notki"
  custom_css: 
    - "mystyles.css"
languages:
  pl:
    title: "Biokompost"
    contentDir: "content"
